version: '3.8'

services:   
  mongo:
    image: mongo
    platform: linux/arm64
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "./mongo/:/docker-entrypoint-initdb.d/"
    ports:
      - 27017:27017